#!/usr/bin/env python3
# Regenerate the embedded boot splash from the master artwork.
#   python3 tools/make_boot_image.py
# Produces a 240x240 BASELINE JPEG (TJpgDec/LovyanGFX-compatible) and emits it
# as a C byte array in receiver_s3_st7789/include/boot_image.h. The master in
# assets/boot_skull_src.jpg is never modified.
from PIL import Image
import os
SRC = "assets/boot_skull_src.jpg"
OUT_JPG = "assets/boot_skull_240.jpg"
OUT_H   = "receiver_s3_st7789/include/boot_image.h"
SIZE = 240
im = Image.open(SRC).convert("RGB").resize((SIZE, SIZE), Image.LANCZOS)
im.save(OUT_JPG, "JPEG", quality=85, optimize=True, progressive=False)
data = open(OUT_JPG, "rb").read()
with open(OUT_H, "w") as f:
    f.write("// AUTO-GENERATED by tools/make_boot_image.py - do not edit by hand.\n")
    f.write("// 240x240 baseline JPEG of the @luca3d_designs boot artwork.\n")
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write("static const uint32_t boot_image_jpg_len = %d;\n" % len(data))
    f.write("static const uint8_t boot_image_jpg[%d] = {\n" % len(data))
    for i in range(0, len(data), 16):
        f.write("  " + ",".join("0x%02X" % b for b in data[i:i+16]) + ",\n")
    f.write("};\n")
print("boot_image.h:", len(data), "bytes JPEG embedded")
